use_frameworks!

platform :ios, '12.0'

target 'ATSwiftPhotoGallery_Example' do
  pod 'ATSwiftPhotoGallery', :path => '../'

  target 'ATSwiftPhotoGallery_Tests' do
    inherit! :search_paths

    
  end
end
